version: '3.3'
services:
 cyberchase:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: "cyberchase"
   MYSQL_ROOT_PASSWORD: "cyber@2020"
  ports:
   - "3306:3306"
 table:
    build: ./Database
 login:
    build: ./Login
    ports:
      - "8000:8000"
