version: '2'
services:
 cyberchase:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: "cyber@2020"
   MYSQL_DATABASE: "cyberchase"
  ports:
   - "3306:3306"
  expose: 
   - "3306"
 createtable:
    restart: on-failure
    build: ./Database
    depends_on:
      - login
    links:
      - cyberchase 
 login:
    restart: on-failure
    build: ./Login
    depends_on: 
      - cyberchase
    links: 
      - cyberchase
    ports:
      - "8000:8000"
    expose:
      - "8000"
 register:
    restart: on-failure
    build: ./Register
    depends_on: 
      - cyberchase
    links: 
      - cyberchase
    ports:
      - "8002:8002"
    expose:
      - "8002"
 forgot:
    restart: on-failure
    build: ./Forgot 
    depends_on:
      - login
    links:
      - cyberchase
      - forgotlog
    ports:
      - 8003:8003
 forgotlog:
    image: mongo
    restart: always
 frontend:
    build: ./FrontEnd
    ports:
      - "80:3000"
    links:
      - login
      - register
