version: '2'
services:
 cyberchase:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  volumes: 
   - ./Database:/docker-entrypoint-initdb.d/:ro
  environment:
   MYSQL_ROOT_PASSWORD: "cyber@2020"
  ports:
   - "3306:3306"
  expose: 
   - "3306"
 login:
    build: ./Login
    depends_on: 
      - cyberchase
    links: 
      - cyberchase
    ports:
      - "8000:8000"
 register:
    build: ./Register
    depends_on: 
      - cyberchase
    links: 
      - cyberchase
    ports:
      - "8002:8002"
 frontdnd:
    build: ./FrontEnd
    ports:
      - "80:3000"
